### ISSUE TITLE
[Bug]: Program opens to a black screen after first installation

### ISSUE THREAD

**Issue by BLCK-B** [BLCK-B/MusicReleaseTracker#98]
### Guidelines

- [X] I have searched the issue tracker for similar issues.
- [X] This issue contains only one bug or bugs with a common origin.

### MusicReleaseTracker version

9.1

### Operating system

Windows 10 Intel Surface 3

### Bug description and reproduction steps

User reported.

### Additional information

![MRT screen shot](https://github.com/user-attachments/assets/0c813511-4551-453b-bf1b-eaef9a0b8cdf)

**Comment by BLCK-B** [comment]
On a VM the reproduction is to simply try to install and run. By extension, on my system removing the .json settings files causes the black screen.
Fatal exception is thrown on the startup, terminating the backend and Electron can't be served on a port. On a second run, the file exists and the error does not happen. Settings system was rewritten in v9.
```
SEVERE: settings file could not be read
java.io.FileNotFoundException: C:\Users\User\AppData\Roaming\MusicReleaseTracker\MRTsettings.json (The system cannot find the file specified)
	at java.base@22.0.2/java.io.FileInputStream.open0(Native Method)
	at java.base@22.0.2/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base@22.0.2/java.io.FileInputStream.<init>(FileInputStream.java:152)
	at com.fasterxml.jackson.core.TokenStreamFactory._fileInputStream(TokenStreamFactory.java:318)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1219)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3313)
	at com.blck.MusicReleaseTracker.JsonSettings.SettingsIO.readJsonFile(SettingsIO.java:98)
	at com.blck.MusicReleaseTracker.JsonSettings.SettingsIO.readSetting(SettingsIO.java:116)
	at com.blck.MusicReleaseTracker.GUIController.getThemeConfig(GUIController.java:150)
	at com.blck.MusicReleaseTracker.FrontendAPI.ApiController.getThemeConfig(ApiController.java:96)
	at java.base@22.0.2/java.lang.reflect.Method.invoke(Method.java:580)
```

In one instance on a VM, the file seems to have been created with illegal whitespace content. This should be addressed - recreate on read errors.

```
SEVERE: settings file could not be read

com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2572)
	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2598)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._throwInvalidSpace(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2509)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:673)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4934)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3313)
	at com.blck.MusicReleaseTracker.JsonSettings.SettingsIO.readJsonFile(SettingsIO.java:98)
	at com.blck.MusicReleaseTracker.JsonSettings.SettingsIO.readAllSettings(SettingsIO.java:125)
	at com.blck.MusicReleaseTracker.GUIController.settingsOpened(GUIController.java:140)
	at com.blck.MusicReleaseTracker.FrontendAPI.ApiController.settingsOpened(ApiController.java:101)
	at java.base@22.0.2/java.lang.reflect.Method.invoke(Method.java:580)
```

On a side note, I should find a way to crash it explicitly on severe errors and provide some dialogue.

**Comment by BLCK-B** [comment]
The issue is in `electron-main.js`. The `app.whenReady()` starts backend and frontend at the same time. A request comes through before backend's initialisation. The solution on my mind is an async future of a isReady request.

**Comment by BLCK-B** [comment]
Race condition was fixed using polling, which is at least better than fixed wait. Json parsing exception within the IOException now triggers settings defaulting.

**Comment by BLCK-B** [comment]
Found this issue again. Seems to be related to Electron caching.

**Comment by BLCK-B** [comment]
Cache only made troubleshooting more difficult. The root issue was related to working directory. Running exe manually worked since the externalised static folder was next to the exe. I had to set a working directory in Electron, otherwise the backend points to incorrect resource location.
